import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import MyProvider from './contexts/MyProvider';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Poppins } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const poppins = Poppins({ subsets: ['latin'], weight: ['200', '400', '600'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>UDO chat app</title>
      </head>
      <body className={poppins.className}>
        <Analytics />
        <SpeedInsights />
        <MyProvider>{children}</MyProvider>
      </body>
    </html>
  );
}
